name = "city-chain-server"
main = "server.js"
compatibility_date = "2026-06-29"

[[durable_objects.bindings]]
name = "CityChainServer"
class_name = "CityChainServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CityChainServer"]

[observability.logs]
enabled = false
invocation_logs = true